import { DataState } from "../Context/Context";
import FilterItem from "./FilterItem.jsx";
import SearchBar from "./SearchBar.jsx";

export default function Filter() {
    const options = ["none", "someOption", "otherOption"];
    const { setEnd, setSector, setRegion, setTopic, setPestle, setSource, setSwot, setCountry, setCity, } = DataState();
    const filterTypes = [
        {
            type: "sector",
            options: [
                '', 'Aerospace & defence',
                'Automotive', 'Construction',
                'Energy', 'Environment',
                'Financial services', 'Food & agriculture',
                'Government', 'Healthcare',
                'Information Technology', 'Manufacturing',
                'Media & entertainment', 'Retail',
                'Security', 'Support services',
                'Tourism & hospitality', 'Transport',
                'Water'
            ],
            set: setSector
        },
        {
            type: "topic",
            options: [
                '',
                '3D',
                'Washington',
                'administration',
                'agriculture',
                'aquaculture',
                'artificial intelligence',
                'asylum',
                'automaker',
                'bank',
                'battery',
                'biofuel',
                'brexit',
                'building',
                'business',
                'capital',
                'car',
                'carbon',
                'change',
                'city',
                'climate',
                'climate change',
                'clothing',
                'coal',
                'communication',
                'consumer',
                'consumption',
                'crisis',
                'data',
                'debt',
                'demand',
                'economic',
                'economic growth',
                'economy',
                'election',
                'electricity',
                'emission',
                'energy',
                'export',
                'factory',
                'farm',
                'finance',
                'food',
                'fossil fuel',
                'fracking',
                'gamification',
                'gas',
                'gasoline',
                'gdp',
                'government',
                'greenhouse gas',
                'growth',
                'ice',
                'industry',
                'inflation',
                'information',
                'infrastructure',
                'interest rate',
                'investment',
                'market',
                'material',
                'money',
                'nuclear',
                'oil',
                'peak oil',
                'plastic',
                'policy',
                'politics',
                'pollution',
                'population',
                'power',
                'production',
                'resource',
                'revenue',
                'risk',
                'robot',
                'security',
                'shale gas',
                'shortage',
                'software',
                'storm',
                'strategy',
                'tax',
                'technology',
                'tension',
                'terrorism',
                'tourist',
                'trade',
                'transport',
                'transportation',
                'unemployment',
                'vehicle',
                'war',
                'water',
                'wealth',
                'work',
                'worker',
                'workforce'],
            set: setTopic,
        },
        {
            type: "region",
            options: [
                '', 'Africa',
                'Asia', 'Central Africa',
                'Central America', 'Central Asia',
                'Eastern Africa', 'Eastern Asia',
                'Eastern Europe', 'Europe',
                'Northern Africa', 'Northern America',
                'Northern Europe', 'Oceania',
                'South America', 'South-Eastern Asia',
                'Southern Africa', 'Southern Asia',
                'Southern Europe', 'Western Africa',
                'Western Asia', 'Western Europe',
                'World', 'world'
            ],
            set: setRegion,
        },
        {
            type: "country",
            options: ['',
                'Algeria',
                'Angola',
                'Argentina',
                'Australia',
                'Austria',
                'Azerbaijan',
                'Belize',
                'Brazil',
                'Burkina Faso',
                'Canada',
                'China',
                'Colombia',
                'Cyprus',
                'Denmark',
                'Egypt',
                'Estonia',
                'Ethiopia',
                'Gabon',
                'Germany',
                'Ghana',
                'Greece',
                'Hungary',
                'India',
                'Indonesia',
                'Iran',
                'Iraq',
                'Japan',
                'Jordan',
                'Kazakhstan',
                'Kuwait',
                'Lebanon',
                'Liberia',
                'Libya',
                'Malaysia',
                'Mali',
                'Mexico',
                'Morocco',
                'Niger',
                'Nigeria',
                'Norway',
                'Oman',
                'Pakistan',
                'Poland',
                'Qatar',
                'Russia',
                'Saudi Arabia',
                'South Africa',
                'South Sudan',
                'Spain',
                'Syria',
                'Turkey',
                'Ukraine',
                'United Arab Emirates',
                'United Kingdom',
                'United States of America',
                'Venezuela'],
            set: setCountry,
        },
        {
            type: "pestle",
            options: ['',
                'Economic',
                'Environmental',
                'Healthcare',
                'Industries',
                'Lifestyles',
                'Organization',
                'Political',
                'Social',
                'Technological'],
            set: setPestle,
        },
        {
            type: "source",
            options: [],
            set: setSource,
        },
        // {
        //     type: "end",
        //     options: [],
        //     set: setEnd,
        // },
    ];

    const setter = [setSector];

    let i = 0;
    return (
        <div className="">
            <div className="bg-slate-900 h-auto lg:p-4 p-2 h-auto text-slate-200 flex flex-row flex-wrap justify-start items-start">
                {filterTypes.map((filter) =>
                    <SearchBar options={filter.options} setOptions={filter.set} key={filter.type} type={filter.type} />
                )}
            </div>
        </div>
    )
}